#                   numpy assignment

Name:-Yash solanki

Reg email id:-yash87015@gmail.com

Course name:-Data analytic

Assignment name:-numpy assignment

Submission date:-not declare

Git link:-https://github.com/Yash87015/YASH (in git hub use assignment folder )

# theoretical Questions:

 ## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

 ### Ans

→ NumPy is a programming library designed for the
Python language. It enhances Python by providing
support for large, multi-dimensional arrays and matrices. In addition, NumPy offers a wide range of high-level mathematical functions specifically designed to operate on these arrays.

→  NumPy is an open-source library in the Python language. (https://numpy.org/)

→ NumPy is a fundamental Python library for scientific computing and data analysis, providing highly optimized multidimensional arrays that enable fast and efficient numerical operations, significantly enhancing Python's capabilities for handling large datasets and complex mathematical calculations compared to standard Python lists, especially when dealing with large-scale data processing tasks due to its optimized C-based implementation.

→ Key advantages of NumPy:

1) Performance:
NumPy arrays are stored in contiguous memory blocks and utilize compiled C code for operations, resulting in significantly faster execution times compared to Python lists, especially for large datasets and vectorized operations.

2) Multidimensional Arrays:
NumPy's core data structure is the 'ndarray' (N-dimensional array), allowing for seamless manipulation of matrices, vectors, and higher-dimensional data structures commonly encountered in scientific computing.

3) Vectorized Operations:
NumPy enables performing operations on entire arrays element-wise, eliminating the need for explicit loops and leading to cleaner, more concise code while maintaining high performance.

4) Integration with other libraries:
NumPy serves as a foundation for many other scientific Python libraries like SciPy, Pandas, and Matplotlib, allowing for smooth data exchange and complex analysis pipelines.

5) Mathematical functions:
NumPy provides a rich collection of mathematical functions like trigonometric operations, linear algebra routines, and statistical calculations, readily accessible for scientific computations.

→ NumPy provides a comprehensive suite of mathematical functions, enabling users to perform addition, subtraction, multiplication, and more on arrays. Broadcasting, a key feature, simplifies operations between arrays of different shapes, enhancing code efficiency and readability.

→ Universal Functions (ufuncs): NumPy’s funcs operate element-wise on arrays, facilitating fast computations across entire arrays without explicit looping. Functions like np.sin(), np.cos(), np.exp(), and np.sqrt() expedite complex mathematical calculations efficiently.


**How NumPy enhances Python for numerical operations**

1) Efficient data storage:-Unlike Python lists, NumPy arrays store data in a homogeneous manner, with all elements having the same data type, leading to optimized memory usage.

2) Optimized algorithms:
By leveraging compiled C code, NumPy can perform complex mathematical operations on large datasets significantly faster than using standard Python loops.

3) Simplified syntax:
NumPy provides a user-friendly interface for performing complex array manipulations with intuitive syntax, making it easier to write and understand scientific computing code.

**use cases of numpy**

1) Data Analysis and Preprocessing: NumPy is widely used in data analysis tasks, including data cleaning, manipulation, and transformation, due to its efficient array operations and mathematical functionalities.

2) Scientific Computing: Applications in physics, biology, engineering, and finance leverage NumPy for simulations, solving differential equations, numerical integration, and more.

3) Machine Learning: NumPy forms the backbone of many machine learning algorithms by handling data representation and mathematical computations efficiently, supporting tasks like feature extraction, data normalization, and model evaluation.







## 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

### Ans

→ 'Mean' & 'Average' are not the same thing. They are frequently used interchangeably, but they should not even be. The np.mean() method returns the arithmetic mean, but the np.average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average.


In NumPy, the np.mean() and np.average() functions are used to calculate the arithmetic mean across an array, but they have some differences:

→ np.mean(): Returns the arithmetic mean.

→ np.average(): Returns the algebraic mean by default, but can also be used to calculate a weighted average.

lets see in details
1) np.mean():-
→ The term "mean" often refers to the "arithmetic mean", which is the sum of a set of numbers divided by the total number of the numbers in the set.

→Syntax:numpy.mean(a, axis=None, dtype=None, **kwargs)(we see with examples as well)
→ axis:-This setting establishes the axis along which the arithmetic means are calculated.
→ dtype:-	This option specifies the data type used to compute the mean.

→ A mean is the summation of all elements divided by the total number of elements. This signifies that they all have the same weight or are only measured once. This means :
(1+2+3+4+5+6+7+8+9+10)/10=5.5

→ np.mean() accepts a few arguments that np.average() does not. One of the most important is the dtype argument, which allows you to specify the data type that will be employed in the computation.

2) np.average():-
→ The term "average" refers to a variety of computations, the "arithmetic mean" is one of them. Other terms include 'median,' 'mode,' 'weighted mean,' 'interquartile mean,' and a variety of others.

→ numpy.average(), on the contrary, allows you to compute a Weighted Mean, with each value in your array having a distinct weight.

→ Syntax:-numpy.average(a, axis=None, weights=None, **kwargs)

→ A weighted mean includes elements with varying weights. It can be hard to imagine, so we'll envision the weighting fits more comfortably over the numbers and looks something like this:

(0*10 + 1*9 + 2*8 + 3*7 + 4*6 + 5*5 + 6*4 + 7*3 + 8*2 + 9*1  )/55=3.6

**Difference between np.average() and np.mean()**

→ Many more arguments, such as dtype, out, where, and others, are available in the np.mean() method that is not accessible in the np.average() function.

→ If the weights option is specified, the np.average() function may compute a weighted mean, but np.mean() cannot.

→ Since np.average does not take into consideration boolean masks, it will compute the average over the entire collection of data. While the np.mean() method takes into account boolean masks, compute the mean solely across unmasked data.

→ if weight is define then we use .average() and if necessary use dtype fuction need than we use .mean().there where whould be use one over other

In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
weight1 = np.array([9,8,7,6,5,4,3,2,1,0])
print(np.mean(a))
print(np.average(a))#here we see in average weight is not given thats why output will be same
print(np.average(a,axis=0,weights=weight1))

5.5
5.5
3.6666666666666665


In [13]:
print(np.mean(a,dtype=float))
print(np.average(a,dtype=float))#see average doesnt support dtype

5.5


TypeError: _average_dispatcher() got an unexpected keyword argument 'dtype'

## 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

### Ans
You can reverse a NumPy array using these functions: np.flip(), np.fliplr() and np.flipud().

→ np.flip():-This function reverses the order of elements in an array along the specified axis. If no axis is specified, it reverses the entire array.

→ np.flipud(): This function flips an array vertically (up/down)

→ np.fliplr(): This function flips an array horizontally (left/right).

→ lests see with 1D and 2D arry example

In [2]:
b=np.array([1,2,3])#1d array
c=np.array([[1,2,3],[4,5,6]])#2D array

In [ ]:
#lets see np.flip()
print(np.flip(b))

[3 2 1]


In [ ]:
print(np.flip(c))

[[6 5 4]
 [3 2 1]]


In [ ]:
print(np.flip(c,axis=0))#reverse row
print(np.flip(c,axis=1))#reverse column

[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [ ]:
#np.flipud()
print("for 1d array:",np.flipud(b))
print("for 2d array:",np.flipud(c,))

for 1d array: [3 2 1]
for 2d array: [[4 5 6]
 [1 2 3]]


In [ ]:
print(np.fliplr(c))#np.fliplr does not work in 1d array

[[3 2 1]
 [6 5 4]]


In [9]:
#we cane use silicing also to filip the element
print("using silicing array:",b[::-1])#to reverse rows.
print("using silicing array:",c[::-1])
print("using silicing array:",c[::-1,::-1])#reverse both axis
print("using silicing array:",c[:,::-1])#to reverse columns.


using silicing array: [3 2 1]
using silicing array: [[4 5 6]
 [1 2 3]]
using silicing array: [[6 5 4]
 [3 2 1]]
using silicing array: [[3 2 1]
 [6 5 4]]


## 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

### Ans
→ we can determine the data useing np.dtype function thats give output value as data type of element in numpy array

→ np.dtype:-Object to be converted to a data type object.

**importance of data type in memory managment**
→ Data types play a crucial role in memory management and performance by dictating how much memory is allocated to store different data values, allowing the system to optimize storage and perform operations efficiently based on the specific data type, ultimately leading to faster and more reliable programs

→ Efficient memory allocation:Each data type has a predefined size, so when a variable is declared with a specific data type, the system allocates the appropriate amount of memory needed to store that type of data, preventing unnecessary memory usage.

→ Optimized operations:Knowing the data type allows the compiler to perform the correct operations on the data, which can be significantly faster than trying to handle different data types with generic operations.

→ Data integrity:Data types help enforce data integrity by defining the range of values that can be stored in a variable, preventing potential errors from incompatible data types being used in calculations.

→ Example: Integer vs. Floating-point: Storing a whole number (like "10") as an integer requires less memory than storing a decimal value (like "10.5") as a floating-point number. By using the appropriate data type, you can optimize memory usage.

**importance of data type in performance**
→ Impact on performance:

→ (1)Faster execution:-When the system knows the exact data type, it can perform calculations and data manipulations more efficiently, leading to faster program execution.

→ (2)Reduced memory overhead:-By allocating the correct amount of memory for each data type, you can minimize unnecessary memory usage, especially in applications with large datasets.

**Important considerations when choosing data types**
→ Data size:Select a data type that is appropriate for the expected range of values to avoid unnecessary memory allocation.

→Precision:If high precision is needed, choose a data type that can handle decimal values accurately.

→ Application needs:Consider the specific operations that will be performed on the data to select the most efficient data type.

→ Data types in programming are classifications that specify the kind of data a variable can hold. They are crucial because they define how the data can be used, what operations can be performed on it, and how much memory is allocated for storing it

In [ ]:
a=np.array([1,2,3])
b=np.array([1.1,2.2,3.3])
c=np.array([1,2,3],dtype=np.bool_)#yoy can also define dtype what ever yoy want
d=np.array([1,2,3],dtype=complex)
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
float64
bool
complex128


## 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

### Ans
→ An ndarray is a multi-dimensional array of items of the same type and size. The number of dimensions and items contained in the array is defined with a tuple of N non-negative integers that specify each dimension's size. An ndarray has an associated data-type object which specifies the dtype stored in the ndarray

**Key features of ndarrays**

→ Homogeneous Data Type:All elements within an ndarray must be of the same data type, such as integers, floats, or strings. This enables efficient operations on the array.

→ Multi-dimensional:An ndarray can represent arrays of any number of dimensions, from 1D vectors to 2D matrices to even higher-dimensional arrays.

→ Fixed Size:-Once created, the size (shape) of an ndarray is fixed. Adding or removing elements requires creating a new array.

→ Efficient Operations:-NumPy provides optimized C and Fortran-based implementations for performing mathematical operations on ndarrays, making them significantly faster than native Python lists.

→ Broadcasting:NumPy allows operations between arrays with different but compatible shapes, making it easier to perform complex calculations.

→Vectorization:Instead of using loops, you can perform operations on entire arrays in a single operation, leading to more concise and efficient code.

→Indexing and Slicing:NumPy provides powerful indexing and slicing capabilities to access and modify specific elements or subarrays within an ndarray.

→Interoperability:NumPy ndarrays can easily be integrated with other Python libraries and data structures.

**NumPy's ndarray and standard Python lists are both ways to store collections of data, but they have key differences that make ndarrays particularly powerful for numerical computations**

1) Homogeneous Data Type:

→ ndarray:Elements in an ndarray must all be of the same data type (e.g., integers, floats, etc.). This allows for efficient memory usage and faster operations.

→ List:Lists can contain elements of different data types (e.g., integers, strings, other lists) within the same list.


2) Fixed Size:

→ ndarray: The size of an ndarray is fixed at creation. Changing the size requires creating a new array.

→ List: Lists are dynamic and can grow or shrink as needed.


3) Vectorized Operations:

→ ndarray:ndarrays support vectorized operations, meaning you can perform mathematical operations on entire arrays without writing explicit loops. This is significantly faster than looping over a list in Python.

→List:Lists do not support vectorized operations. You need to loop through the list to perform operations on individual elements.


4) Broadcasting:

→ ndarray: NumPy supports broadcasting, which allows you to perform operations on arrays with different but compatible shapes.

→ List: Lists do not support broadcasting.

5) Memory Efficiency:

→ndarray: ndarrays are more memory efficient than lists for storing large amounts of numerical data due to their homogeneous data type and contiguous memory allocation.

6) Functionality:

→ ndarray:NumPy offers a rich set of functions and methods specifically designed for working with arrays, including mathematical operations, linear algebra, statistical analysis, and more.

→ List:Python lists offer general-purpose functionality for adding, removing, and manipulating elements.

**In summary**

Use ndarrays for numerical computations involving large amounts of data, where speed and efficiency are crucial.
Use lists for storing collections of heterogeneous data types or when you need dynamic resizing.

## 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

### Ans

→ NumPy arrays offer significant performance advantages over Python lists for large-scale numerical operations due to their underlying implementation and optimized features.that we see in above question

→ NumPy arrays are more memory efficient compared to Python lists. They store homogeneous data types in contiguous memory blocks, reducing memory overhead and improving memory utilization, especially for large datasets.

→ Lower Memory Consumption: NumPy arrays are more compact than Python lists.

**Examples of Performance Benefits**

→ Element-wise Operations:NumPy arrays outperform Python lists by a significant margin when performing element-wise operations like addition, subtraction, multiplication, and division.

→ Linear Algebra:NumPy provides highly optimized functions for linear algebra operations like matrix multiplication, eigenvalue decomposition, and solving linear systems, which are much faster than their Python equivalents.

→ Statistical Operations:NumPy's statistical functions, such as mean, median, standard deviation, and correlation, are optimized for performance and can handle large datasets efficiently.

**In Summary**

→ NumPy arrays are the go-to choice for large-scale numerical operations in Python due to their optimized implementation, vectorized operations, and memory efficiency. They offer significant performance improvements over Python lists, making them essential for scientific computing, data analysis, and machine learning tasks.

→ Python Lists : You need to use a loop to iterate over each element and perform the addition. This approach is slow due to the overhead of Python's dynamic type checking and the repeated method calls.

→ NumPy Arrays : You can simply use the + operator on two arrays, and NumPy will perform the addition in a highly optimized manner. This operation is executed much faster and more efficiently. Overall, NumPy arrays provide substantial performance benefits for large-scale numerical operations, including improved memory efficiency, faster computations, reduced overhead, and advanced features that are crucial for high-performance scientific and data analysis tasks.

## 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

### Ans

→ In NumPy, vstack and hstack are functions used to stack arrays vertically and horizontally, respectively. Here's a comparison:

1) vstack():VSTACK returns the array formed by appending each of the array arguments in a row-wise fashion. The resulting array will be the following dimensions:

→ Rows: the combined count of all the rows from each of the array arguments.

→ Columns: The maximum of the column count from each of the array arguments.

→ Stacks arrays vertically (along the first axis, i.e., rows).

→ The arrays must have the same number of columns.


2) hstack():HSTACK returns the array formed by appending each of the array arguments in a column-wise fashion. The resulting array will be the following dimensions:

→ Rows    The maximum of the row count from each of the array arguments.

→ Columns    The combined count of all the columns from each of the array arguments.

→ Stacks arrays horizontally (along the second axis, i.e., columns).

→ The arrays must have the same number of rows.

**key difference**

→ Stacking direction: vstack stacks along rows, while hstack stacks along columns.

→ Dimension requirement: vstack requires matching column counts, while hstack requires matching row counts.

→ If the axis is set to 0, it works as vstack and if the axis is 1, it works as hstack.

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("vstack operatio:",np.vstack((a,b)))
print("hstack operatio:",np.hstack((a,b)))

vstack operatio: [[1 2 3]
 [4 5 6]]
hstack operatio: [1 2 3 4 5 6]


In [ ]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[7,8,9],[10,11,12]])
print("vstack operatio:",np.vstack((c,d)))
print("hstack operatio:",np.hstack((c,d)))

vstack operatio: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
hstack operatio: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

### Ans

**diffrence between fliplr() and flipud()**

→ In NumPy, fliplr() flips an array horizontally (left to right), while flipud() flips an array vertically (up to down), meaning fliplr() reverses the columns of a matrix while flipud() reverses the rows, regardless of the array's dimensionality.

**Key points**

Axis of Flipping:

fliplr(): Flips along the second axis (column index).
flipud(): Flips along the first axis (row index).

**Impact on different array dimensions**

→ 1D array: Both fliplr() and flipud() will simply reverse the order of elements in the array as there is only one axis.

→ 2D array (matrix):

fliplr(): Columns are reversed.

flipud(): Rows are reversed.

→ Higher dimensional arrays: The flipping operation will only affect the specified axis (second axis for fliplr, first axis for flipud) while leaving other dimensions unchanged.

→ View vs. Copy:Both fliplr() and flipud() return a view of the original array, meaning changes to the flipped array will also affect the original array.

→ np.flip() function:NumPy also provides a more general flip() function where you can explicitly specify the axis along which to flip.

In [ ]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print("flipud operation on array a:\n",np.flipud(a))
print("fliplr operation on array b:\n",np.fliplr(b))
print("flipud operation on array a:\n",np.flipud(b))

flipud operation on array a:
 [3 2 1]
fliplr operation on array b:
 [[3 2 1]
 [6 5 4]]
flipud operation on array a:
 [[4 5 6]
 [1 2 3]]


## 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### Ans
→ In NumPy, the split() function is used to split an array into multiple sub-arrays along a specified axis. However, it has a limitation: it requires the array to be split into equal-sized sub-arrays. If the array cannot be divided evenly, the function will raise an error.

→ To handle uneven splits, you should use the array_split() function instead. Here's how it works:

 **Functionality of arry_split()**

→ array_split() splits an array into multiple sub-arrays along a specified axis, even if the splits are not equal.

→The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful for dividing data into chunks or segments, especially when working with large datasets. Here a detailed look at how array_split() works and how it handles uneven splits

→Syntax :
numpy.array_split(ary, indices_or_sections, axis=0)

→ ary : The input array to be split.

→ axis : Axis along which to split the array. The default is 0, meaning splitting along the first axis (rows for 2D arrays).

→ indices_or_sections : Defines how to split the array:

**Handling Uneven Splits**

→ If the array cannot be divided equally, array_split() distributes the remaining elements as evenly as possible among the sub-arrays. The first few sub-arrays may have one more element than the others.

→If the number of elements is not perfectly divisible, some sub-arrays will have one more element than others. For example, if you split an array with 10 elements into 3 parts, you will get two sub-arrays with 3 elements each and one sub-array with 4 elements.

→ The array is split at the specified indices. The resulting sub-arrays will be the segments between these indices.

→ If the specified indices do not evenly divide the array, the last sub-array will contain the remaining elements.

In [11]:
#Splitting into Equal Parts
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array_split(a,5))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [13]:
#Splitting with Uneven Parts
b=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array_split(b,3))


[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


## 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

### Ans
→ Vectorization and broadcasting are techniques in NumPy that help speed up array operations and make them more efficient

→ lets see each one in details

1) vectorization:-This technique applies an operation to an entire array at once, instead of looping over each element. Vectorization uses pre-compiled functions and mathematical operations, and delegates operations to C. This makes vectorized operations faster and more efficient than using for loops.

→ The a1 + a2 operation performs element-wise addition on the entire arrays simultaneously, without the need to loop through each element individually in Python.

→ This is due to lower-level optimizations and reduced overhead associated with Python’s dynamic typing and interpreted nature.


2) Broadcasting:- Broadcasting works by checking if arrays are compatible and stretching smaller dimensions to match larger ones. Broadcasting avoids unnecessary data copies and usually leads to efficient algorithm implementations.

→ In the second example, the scalar value 2 is effectively "broadcast" to match the shape of arr1, allowing the addition operation to be applied element-wise even though the dimensions are different

→ this technique used in NumPy to perform arithmetic operations on arrays of different shapes in a way that aligns dimensions automatically. It allows operations between arrays of different sizes by "broadcasting" the smaller array across the larger one.

**Here are some rules for broadcasting**

→ If two arrays are the same length in a dimension, that dimension is operated on element-wise.

→ If one array has a value in a dimension and the other array is size 1 in that dimension, the value is broadcast and used with each item in the other array.

→ If the arrays are different sizes and neither is size 1, broadcasting can't be performed.

***How They Contribute to Efficient Array Operations***

Speed : Vectorization and broadcasting both leverage efficient low-level implementations, reducing the need for Python-level loops and computations. This results in faster execution times.

Memory Efficiency : Broadcasting avoids the need for creating large intermediate arrays, as it operates directly on existing arrays by broadcasting smaller arrays as needed.

Code Simplicity : Both techniques enable more concise and readable code, avoiding the complexity of nested loops and manual array manipulations.

→ Improved performance: By avoiding explicit Python loops, computations are significantly faster, especially when dealing with large datasets.

→ Concise code: Vectorized operations often result in more readable and concise code.

→ Flexibility: Broadcasting allows operations on arrays with different shapes, making data manipulation easier.

In [14]:
#vectorization
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)

[5 7 9]


In [15]:
#brodcasting
arr1 = np.array([1, 2, 3])
scalar = 2
result = arr1 + scalar
print(result)

[3 4 5]


In [16]:
#adding 2D and 1D dime
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
print(a+b)

[[ 8 10 12]
 [11 13 15]]


#Practical Questions:

## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

### Ans


In [19]:
#create 3x3 numply between 1 to 100
a=np.random.randint(1,100,(3,3))
print(a)

[[97 39  8]
 [33 35  4]
 [70 78 72]]


In [20]:
#interchage rows and column using transpose
a.T

array([[97, 33, 70],
       [39, 35, 78],
       [ 8,  4, 72]])

## 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

### Ans

In [22]:
#generate 1D array with 10 elements.
a=np.arange(10)
print(a)

b=a.ndim
print("dimension of array is:",b)

[0 1 2 3 4 5 6 7 8 9]
dimension of array is: 1


In [23]:
#reshape of array into 2x5
a=a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
#reshape of array into 5x2
a=a.reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

### Ans

In [14]:
#create a 4x4 numpy array with random float values
a=np.random.rand(4,4)
print(a)

[[0.8197067  0.99290705 0.74567811 0.95365818]
 [0.1940247  0.77692307 0.65709761 0.72703576]
 [0.40880151 0.81379881 0.09669474 0.14651464]
 [0.597067   0.08232104 0.34557739 0.67812154]]


In [15]:
#add a broder of zeros around it
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.8197067  0.99290705 0.74567811 0.95365818 0.        ]
 [0.         0.1940247  0.77692307 0.65709761 0.72703576 0.        ]
 [0.         0.40880151 0.81379881 0.09669474 0.14651464 0.        ]
 [0.         0.597067   0.08232104 0.34557739 0.67812154 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [16]:
#print the resulting 6x6 array
print("shape of array:",a.shape)

shape of array: (6, 6)


## 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

### Ans

In [33]:
#create array from 10 to 60 with step 5
a=np.arange(10,61,5)
print(a)

[10 15 20 25 30 35 40 45 50 55 60]


## 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

### Ans

In [34]:
#create numpy array of string ['python','numpy','pandas']
a=np.array(['python','numpy','pandas'])
print(a)

['python' 'numpy' 'pandas']


In [36]:
#apply diffrent case transformation (uppercase,lowercase,title)
print("uppercase:",np.char.upper(a))
print("lowercase:",np.char.lower(a))
print("titlecase:",np.char.title(a))


uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
lowercase: ['python' 'numpy' 'pandas']
titlecase: ['Python' 'Numpy' 'Pandas']


## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

### Ans

In [37]:
#generate numpy array of words
a=np.array(["hii , i am learning data toolkit module"])
print(a)

['hii , i am learning data toolkit module']


In [38]:
#insert a space between each character
b=np.char.join(" ",a)
print(b)

['h i i   ,   i   a m   l e a r n i n g   d a t a   t o o l k i t   m o d u l e']


## 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

### Ans

In [39]:
#create 2 2D numpy arrays
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [41]:
#perform element wise operation
print("addition:",a+b)
print("\nsubtraction:",a-b)
print("\nmultiplication:",a*b)
print("\ndivision:",a/b)

addition: [[ 8 10 12]
 [14 16 18]]

subtraction: [[-6 -6 -6]
 [-6 -6 -6]]

multiplication: [[ 7 16 27]
 [40 55 72]]

division: [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

### Ans

In [42]:
#create 5x5 identity matrix
a=np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
#extract its diogonal element
print(np.diag(a))

[1. 1. 1. 1. 1.]


## 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array?

### Ans

In [22]:
#generate numpy array of 100 random int between 0 to 1000
a=np.random.randint(0,1001,100)
print(a)

[601  61 212 894 722 802 887 803 592 549 733 947 321  46 365 746  80 718
 204 472 300 469 202 913 542 308 193 223 274 876 335 778 142 427 112 476
 451 606 211 732 356 992 583 229 953   5 556 976 808 632 571 380  56   0
 229 893  30 295 733 668 888  12 515 857 107 846 612   3 242   6 916 154
 411 469 909 252 828  32  50 777 214 653 787 530 469 502 206 384 206 631
 701  14 167 488 993 169 414 379 482 735]


In [46]:
#display all prime number in this array
for i in a:
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i)

601
61
887
733
947
193
223
211
229
953
5
571
229
733
857
107
3
653
787
631
701
167
379


## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

### Ans


In [49]:
#create numpy array represnting daily temprature for a mounth 30 temrature from -30 to 30
daily_tem=np.random.randint(-30,31,30)
print(daily_tem)


[-24 -17 -27  10 -17 -15  12 -12 -13 -13 -11   5 -30  23 -18  11 -23 -14
  19   3 -15   0  14  24   7  13 -14 -12  23  -3]


In [51]:
#create weekly temrature using reshaping
weekly_tem=daily_tem.reshape(5,6)
print(weekly_tem)

[[-24 -17 -27  10 -17 -15]
 [ 12 -12 -13 -13 -11   5]
 [-30  23 -18  11 -23 -14]
 [ 19   3 -15   0  14  24]
 [  7  13 -14 -12  23  -3]]


In [52]:
#display weekly average
weekly_avg=np.mean(weekly_tem,axis=1)
print(weekly_avg)


[-15.          -5.33333333  -8.5          7.5          2.33333333]
