why numpy? 

→ already we have c and c++ fastest programming language and numpy is buit using c that why numpy computation is fast 

→ due to array since its store only homogeneous data , numpy array is faster

→ beacuse numpy has homogenous arry that why mathamatic computation is very fast thats why numpy use

→ since  it store homogenous data its can continuous memory location

→ all the modules kept together is called package
→ all maltiple package together is called as libray

→ libray contain python packages and modules

what is library?

***a library is a collaction of pri-written code, that is used to perform comman task***

# numpy

numpy:-numerical python

In [1]:
import numpy as np##2005 by Travis Oliphant

In [2]:
np.__version__

'1.23.5'

what is arange function?
why numpy array is faster  compare to other data stucture?
what is numpy array and matrix difference?
how can you increase dimension?
linear algebra?solve inverse , transpose 

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

numpy stored the data in a numpy array

→ array is a data structure/cointainer  used to store data of some data type its is homogeneus its store the same data type

In [25]:
l = [1,2,3,4,5,6]

In [26]:
ab=np.array(l)

In [12]:
type(ab)#nd means n dimension of array

numpy.ndarray

In [13]:
qw=[1,2,3,4,5,"dyie"]

In [14]:
qc=np.array(qw)

In [15]:
type(qc)

numpy.ndarray

In [16]:
np.array(qw)

array(['1', '2', '3', '4', '5', 'dyie'], dtype='<U21')

In [17]:
ab

array([1, 2, 3, 4, 5, 6])

In [18]:
r=[1,2,3,4,4.5]

In [30]:
qr=np.array(r)

In [31]:
qr.ndim#beacuse only has row only one dimension

1

In [32]:
er=np.array([[1,2,3],[4,5,6]])

In [33]:
er.ndim # now its has row and coloam that has two  dimension

2

In [34]:
er

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
mad=np.matrix([1,2,3,4])

In [37]:
type(mad)

numpy.matrix

In [38]:
mad.ndim

2

In [39]:
mad

matrix([[1, 2, 3, 4]])

matrix has two dimension only not 1 or 3

In [40]:
np.matrix([[[1,2,3,4]]])

ValueError: matrix must be 2-dimensional

In [41]:
#more way to convert array
#np.asarray
#np.array
#np.asanyarray
q=[1,2,3,4,5]

In [42]:
np.asarray(q)

array([1, 2, 3, 4, 5])

In [45]:
qw=np.asarray(q)#intial function to convert array np.array come after this

In [46]:
type(qw)

numpy.ndarray

In [50]:
qe=np.asanyarray([[1,2,3,4]])

In [51]:
qe.ndim

2

In [52]:
qe

array([[1, 2, 3, 4]])

asanyarray will convert the input to the ndarray,but if somthing already in array it will subclass throw it will not do anything(Convert the input to an ndarray, but pass ndarray subclasses throw)

In [53]:
mad

matrix([[1, 2, 3, 4]])

In [54]:
np.asanyarray(mad)

matrix([[1, 2, 3, 4]])

In [58]:
er # accesing of array

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
er[0]

array([1, 2, 3])

In [60]:
er[1]

array([4, 5, 6])

er[0,1]=9#array is mutable

In [63]:
er

array([[1, 9, 3],
       [4, 5, 6]])

In [64]:
er[0,2]=7

In [65]:
er

array([[1, 9, 7],
       [4, 5, 6]])

→ array deep copy and shallow copy

a and array will point to same memory locaion , so if changes is a an array it will reflate on both

In [66]:
a=er#shallow copy

In [67]:
a

array([[1, 9, 7],
       [4, 5, 6]])

In [68]:
er

array([[1, 9, 7],
       [4, 5, 6]])

In [69]:
a[1,2]=8

In [70]:
a

array([[1, 9, 7],
       [4, 5, 8]])

In [71]:
er

array([[1, 9, 7],
       [4, 5, 8]])

In [72]:
#deep copy

In [74]:
c=a.copy()

In [75]:
c

array([[1, 9, 7],
       [4, 5, 8]])

In [76]:
a

array([[1, 9, 7],
       [4, 5, 8]])

In [77]:
c[0,2]=45

In [78]:
c

array([[ 1,  9, 45],
       [ 4,  5,  8]])

In [79]:
a

array([[1, 9, 7],
       [4, 5, 8]])

maltiple approch to generate any array

In [84]:
er=np.fromfunction(lambda i,j:i==j,(3,3))#onstruct an array by executing a function over each coordinate.

#The resulting array therefore has a value ``fn(x, y, z)`` at
#coordinate ``(x, y, z)``.[00 01 02
                       #   10 11 12
                       #   20 21 22]


In [83]:
1==2

False

In [85]:
er

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [86]:
er.ndim

2

In [87]:
er.shape #shape of array

(3, 3)

In [89]:
er.size #shape of size

9

In [93]:
rt=np.fromfunction(lambda i,j:i*j,(3,3))

In [94]:
rt

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [95]:
rt.ndim

2

In [96]:
rt.shape

(3, 3)

In [97]:
rt.size

9

In [98]:
for i in range(5):
    print(i)

0
1
2
3
4


In [100]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [101]:
(i for i in range(5))

<generator object <genexpr> at 0x771a9c372420>

In [106]:
iterator=(i for i in range(5))

In [108]:
np.fromiter(iterator,int)#Create a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [113]:
np.fromstring('22 23 24',sep=" ")

array([22., 23., 24.])

In [114]:
np.fromstring('22 23 24',int,sep=" ")

array([22, 23, 24])

In [126]:
ty="ajay bijay truma fatru"
ty.split(" ")

['ajay', 'bijay', 'truma', 'fatru']

In [125]:
np.array(ty.split(" "))

array(['ajay', 'bijay', 'truma', 'fatru'], dtype='<U5')

In [127]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array also same function called arange

In [132]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [131]:
np.linspace(1,5,10)#Return evenly spaced numbers over a specified interval.give

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
q=np.zeros(5,int)#Return a new array of given shape and type, filled with zeros.

In [12]:
q.ndim

1

In [13]:
q

array([0, 0, 0, 0, 0])

In [23]:
e=np.zeros((3,4,))

In [24]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
e.ndim

2

In [36]:
j=np.ones(((4,3)))

In [37]:
j

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
j.ndim

2

In [39]:
r=[[[[0,2,3],[4,5,6],[7,8,9]]]]

In [41]:
q=np.array(r)

In [42]:
q

array([[[[0, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [43]:
q.ndim

4

In [60]:
e=np.zeros((3,4))

In [61]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

3 D 3 dimension array

In [66]:
r=np.zeros((1,2,3))

In [67]:
r.ndim

3

In [68]:
r

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [70]:
q=np.ones((3,2,3))

In [71]:
q

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
q.ndim

3

In [79]:
e=np.ones((1,1,1,2,3))

In [80]:
e

array([[[[[1., 1., 1.],
          [1., 1., 1.]]]]])

In [81]:
e.ndim

5

In [82]:
qw=np.ones((3,4))

In [83]:
qw

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [84]:
qw.ndim

2

In [88]:
a=qw+7

In [90]:
b=a*2

In [91]:
b

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [92]:
a

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [93]:
b -1

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [94]:
np.eye(3)#Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
e=np.eye(3,dtype=int)

In [98]:
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [99]:
e.ndim

2

In [104]:
np.empty((3,4))#Return a new array of given shape and type, without initializing entries.its means it give in array any number in entry

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [106]:
#random module
import random

In [107]:
random.choices((1,2,3,45,5,6))

[1]

In [109]:
random.choices("ajaaY")

['j']

In [111]:
random.randrange(1,10)

4

In [114]:
random.random()

0.32765372791506986

In [120]:
l=[1,2,3,4,5,6]
random.shuffle(l)

In [121]:
l

[2, 6, 4, 3, 5, 1]

In [125]:
random.uniform(6,14)#Get a random number in the range [a, b) or [a, b] depending on rounding

12.600475097826662

In [126]:
#random number related concept in  numpy

In [129]:
np.random.random_sample()

0.9536583539181515

In [131]:
q=np.random.random_sample((5))

In [132]:
q.ndim

1

In [133]:
q

array([0.25947444, 0.97758117, 0.92659455, 0.5356723 , 0.86033856])

In [137]:
q=np.random.rand(2)

In [140]:
q.ndim

1

In [141]:
q

array([0.15151491, 0.41523961])

In [145]:
q=np.random.rand(2,3)

In [146]:
q

array([[0.84039901, 0.10191138, 0.81946569],
       [0.98007511, 0.01731156, 0.45295096]])

In [147]:
q.ndim

2

In [148]:
np.random.randn(2,3)#Return a sample (or samples) from the "standard normal" distribution.

array([[-0.37392412,  0.31453149, -1.10010456],
       [-0.27580617,  0.12396564,  0.85479583]])

In [151]:
np.random.randint(1,5,size=(3,4))#Return random integers from `low` (inclusive) to `high` (exclusive)

array([[1, 3, 4, 1],
       [4, 3, 1, 3],
       [3, 4, 3, 4]])

In [152]:
arr=np.random.randint(1,5,size=(3,4))

reshaping of array using reshape command

→When reshaping an array in NumPy, the number of elements and order of elements in the array must remain the same. Here are some other conditions that apply to reshaping an array: 
 
Shape
The shape of an array is the number of elements in each dimension. 

***size:-if array size 12 than you can convert in to [4 * 3], [6 * 2], [12 * 1] that you can reshape no other dimension like 3*3 beacuse its resultant give 9 not 12***
 
Dimensions
You can add or remove dimensions, or change the number of elements in each dimension. 
 
Compatibility
The new shape must be compatible with the original shape. For example, you can reshape an 8-element 1D array into a 4-element 2D array, but not into a 3-element 3-rows 2D array. 
 
Data
The reshape function returns a new array with the same data but a different shape. 
 
The reshape() function is useful when working with different dimensions of data, like transforming a 1D array into a 2D array or reshaping a 3D array into a 2D array. 
 


In [158]:
np.reshape(arr,(2,6))

array([[3, 4, 2, 4, 1, 2],
       [2, 3, 1, 1, 1, 1]])

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
    
    
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
    
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the memory layout of
    the underlying array, and only refer to the order of indexing.
    'A' means to read / write the elements in Fortran-like index
    order if `a` is Fortran *contiguous* in memory, C-like order
    otherwise.

Returns
-------
reshaped_array : ndarray
    This will be a new view object if possible; otherwise, it will
    be a copy.  Note there is no guarantee of the *memory layout* (C- or
    Fortran- contiguous) of the returned array.

See Also
--------
ndarray.reshape : Equivalent method.

Notes
-----
It is not always possible to change the shape of an array without
copying the data. If you want an error to be raised when the data is copied,
you should assign the new shape to the shape attribute of the array::

 >>> a = np.zeros((10, 2))

 # A transpose makes the array non-contiguous
 >>> b = a.T

 # Taking a view makes it possible to modify the shape without modifying
 # the initial object.
 >>> c = b.view()
 >>> c.shape = (20)
 Traceback (most recent call last):
    ...
 AttributeError: Incompatible shape for in-place modification. Use
 `.reshape()` to make a copy with the desired shape.

The `order` keyword gives the index ordering both for *fetching* the values
from `a`, and then *placing* the values into the output array.
For example, let's say you have an array:

>>> a = np.arange(6).reshape((3, 2))
>>> a
array([[0, 1],
       [2, 3],
       [4, 5]])

You can think of reshaping as first raveling the array (using the given
index order), then inserting the elements from the raveled array into the
new array using the same kind of index ordering as was used for the
raveling.

>>> np.reshape(a, (2, 3)) # C-like index ordering
array([[0, 1, 2],
       [3, 4, 5]])
>>> np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape
array([[0, 1, 2],
       [3, 4, 5]])
>>> np.reshape(a, (2, 3), order='F') # Fortran-like index ordering
array([[0, 4, 3],
       [2, 1, 5]])
>>> np.reshape(np.ravel(a, order='F'), (2, 3), order='F')
array([[0, 4, 3],
       [2, 1, 5]])

Examples
--------
>>> a = np.array([[1,2,3], [4,5,6]])
>>> np.reshape(a, 6)
array([1, 2, 3, 4, 5, 6])
>>> np.reshape(a, 6, order='F')
array([1, 4, 2, 5, 3, 6])

>>> np.reshape(a, (3,-1))       # the unspecified value is inferred to be 2
array([[1, 2],
       [3, 4],
       [5, 6]])

In [166]:
aq=np.reshape(arr,(4,3))#array size will naver change

In [167]:
aq

array([[3, 4, 2],
       [4, 1, 2],
       [2, 3, 1],
       [1, 1, 1]])

In [168]:
aq.shape

(4, 3)

In [169]:
aq.size

12

In [172]:
#case when you dont know reshape of row or colomjust use -(minus)(any number)[-1] for count use row or colom
aq.reshape(4,-1)

array([[3, 4, 2],
       [4, 1, 2],
       [2, 3, 1],
       [1, 1, 1]])

In [173]:
aq.shape

(4, 3)

In [180]:
aq.reshape(-1,4)

array([[3, 4, 2, 4],
       [1, 2, 2, 3],
       [1, 1, 1, 1]])

In [182]:
aq.shape

(4, 3)

In [187]:
aq.reshape(-1,4).base#to see original array

array([[3, 4, 2, 4],
       [1, 2, 2, 3],
       [1, 1, 1, 1]])

In [193]:
qw=aq.reshape(1,6,2)#multiplecation should be array size

In [192]:
aq.ndim

2

In [194]:
qw.ndim

3

condition on numpy

In [196]:
qe=np.random.randint(1,10,(5,6))

In [197]:
qe

array([[9, 1, 6, 4, 3, 6],
       [8, 6, 3, 2, 1, 4],
       [1, 7, 9, 2, 5, 7],
       [1, 9, 7, 3, 9, 3],
       [9, 4, 1, 1, 2, 8]])

In [198]:
qe > 5

array([[ True, False,  True, False, False,  True],
       [ True,  True, False, False, False, False],
       [False,  True,  True, False, False,  True],
       [False,  True,  True, False,  True, False],
       [ True, False, False, False, False,  True]])

In [200]:
qe[qe > 5]#select all the element of qe while condition is true

array([9, 6, 6, 8, 6, 7, 9, 7, 9, 7, 9, 9, 8])

In [202]:
qe[qe<9]

array([1, 6, 4, 3, 6, 8, 6, 3, 2, 1, 4, 1, 7, 2, 5, 7, 1, 7, 3, 3, 4, 1,
       1, 2, 8])

In [203]:
qe


array([[9, 1, 6, 4, 3, 6],
       [8, 6, 3, 2, 1, 4],
       [1, 7, 9, 2, 5, 7],
       [1, 9, 7, 3, 9, 3],
       [9, 4, 1, 1, 2, 8]])

acess the element 

In [206]:
qe[1,4]=5

In [208]:
qe[0][3]

4

In [225]:
qe[3]

array([1, 9, 7, 3, 9, 3])

In [210]:
qe[3][1]

9

In [214]:
#from oth with row 2nd row
qe[0:3]

array([[9, 1, 6, 4, 3, 6],
       [8, 6, 3, 2, 5, 4],
       [1, 7, 9, 2, 5, 7]])

In [217]:
#from oth to 2nd row and oth and 2nd coloum

In [219]:
qe[0:3,(0,2)]

array([[9, 6],
       [8, 3],
       [1, 9]])

In [216]:
qe

array([[9, 1, 6, 4, 3, 6],
       [8, 6, 3, 2, 5, 4],
       [1, 7, 9, 2, 5, 7],
       [1, 9, 7, 3, 9, 3],
       [9, 4, 1, 1, 2, 8]])

silicing on both row and colom together

In [220]:
qe

array([[9, 1, 6, 4, 3, 6],
       [8, 6, 3, 2, 5, 4],
       [1, 7, 9, 2, 5, 7],
       [1, 9, 7, 3, 9, 3],
       [9, 4, 1, 1, 2, 8]])

In [228]:
#from 0th to 2nd row and colom will be 1nd to 3rd
qe[0:3,0:3]

array([[9, 1, 6],
       [8, 6, 3],
       [1, 7, 9]])

In [229]:
qe[0,[0,3]]

array([9, 4])

In [274]:
a1=np.random.randint(1,4,(3,3))
a2=np.random.randint(1,4,(3,3))


In [239]:
a1

array([[2, 1, 3],
       [0, 1, 1],
       [1, 2, 1],
       [2, 3, 1]])

In [240]:
a2

array([[ 4,  1,  8],
       [ 5,  3, 10],
       [10,  5,  6],
       [ 8,  9,  3]])

In [241]:
a1 + a2 #always index wise do operation not matrix

array([[ 6,  2, 11],
       [ 5,  4, 11],
       [11,  7,  7],
       [10, 12,  4]])

In [242]:
a1,a2

(array([[2, 1, 3],
        [0, 1, 1],
        [1, 2, 1],
        [2, 3, 1]]),
 array([[ 4,  1,  8],
        [ 5,  3, 10],
        [10,  5,  6],
        [ 8,  9,  3]]))

In [243]:
4/0

ZeroDivisionError: division by zero

In [244]:
a1/0

/tmp/ipykernel_105/1504525615.py:1: RuntimeWarning: divide by zero encountered in divide
  a1/0
/tmp/ipykernel_105/1504525615.py:1: RuntimeWarning: invalid value encountered in divide
  a1/0


array([[inf, inf, inf],
       [nan, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [245]:
0/a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [247]:
#matrix mul

In [260]:
a1


array([[1, 1, 2],
       [1, 2, 1],
       [2, 3, 2],
       [3, 1, 1]])

In [261]:
a2

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [275]:
a1 @ a2

array([[14,  7,  9],
       [21, 11, 12],
       [14,  8,  7]])

In [276]:
a1 * a2

array([[2, 2, 2],
       [9, 6, 2],
       [3, 3, 3]])

In [278]:
np.dot(a1,a2) #another way of matrix multi

array([[14,  7,  9],
       [21, 11, 12],
       [14,  8,  7]])

In [279]:
a1,a2

(array([[1, 2, 2],
        [3, 3, 2],
        [1, 3, 1]]),
 array([[2, 1, 1],
        [3, 2, 1],
        [3, 1, 3]]))

brodcasting

In [322]:
a=np.zeros((3,3))

In [303]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [323]:
b=np.array([1,2,3])

In [312]:
b

array([1, 2, 3])

In [325]:
c=b+a

In [326]:
c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

transpose:-transpose means convert row to colomb and colomb to row

In [316]:
a=np.array([[1,2,3,4]])

In [317]:
a

array([[1, 2, 3, 4]])

In [318]:
a.ndim

2

In [319]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [320]:
b

array([1, 2, 3])

In [327]:
c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [328]:
c.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [2]:
a1=np.random.randint(1,4,(3,3))

In [3]:
a1

array([[2, 3, 1],
       [1, 3, 1],
       [2, 3, 1]])

In [4]:
a2=np.random.randint(1,5,(3,3))

In [5]:
a2

array([[2, 4, 1],
       [1, 4, 1],
       [3, 1, 3]])

In [7]:
c=a1.flatten()#Return a copy of the array collapsed into one dimension.

In [8]:
c

array([2, 3, 1, 1, 3, 1, 2, 3, 1])

In [9]:
c.ndim

1

In [10]:
e=np.array([1,2,3,4,5])

In [11]:
e

array([1, 2, 3, 4, 5])

In [12]:
e.ndim

1

In [16]:
t=np.expand_dims(e,axis=0)#Expand the shape of an array.Insert a new axis that will appear at the `axis` position in the expanded array shape.

In [17]:
t#in axis 0 means rows or (x axis) and 1 means colom(y axis)

array([[1, 2, 3, 4, 5]])

In [18]:
t.ndim

2

In [19]:
t1=np.expand_dims(e,axis=1)

In [21]:
t1.ndim

2

In [22]:
t1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [23]:
qe=np.ones((3,4))

In [24]:
qe

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
u=np.expand_dims(qe,axis=0)

In [27]:
u

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
u.ndim

3

In [29]:
qe.ndim

2

In [2]:
a=np.array(([1],[2],[3]))

In [3]:
a.ndim

2

In [4]:
o=np.expand_dims(a,axis=1)

In [5]:
o

array([[[1]],

       [[2]],

       [[3]]])

In [6]:
o.ndim

3

In [7]:
a.ndim

2

squeezing of dimension

→ squeezing the dime by 1 dimension 

In [8]:
o1=np.squeeze(o)

In [9]:
o1.ndim

1

In [10]:
o.ndim

3

In [15]:
o.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [16]:
o

array([[[1]],

       [[2]],

       [[3]]])

In [17]:
a

array([[1],
       [2],
       [3]])

In [18]:
a.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [47]:
a1=np.random.randint(1,4,(3,3))

In [25]:
a1

array([[1, 3, 1],
       [3, 1, 3],
       [2, 1, 3]])

In [26]:
np.repeat(a1,3)

array([1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 2, 2, 2, 1,
       1, 1, 3, 3, 3])

In [28]:
np.repeat(a1,3,axis=1)

array([[1, 1, 1, 3, 3, 3, 1, 1, 1],
       [3, 3, 3, 1, 1, 1, 3, 3, 3],
       [2, 2, 2, 1, 1, 1, 3, 3, 3]])

In [30]:
np.roll(a,1)

array([[3],
       [1],
       [2]])

In [31]:
a

array([[1],
       [2],
       [3]])

In [32]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [33]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [34]:
r=np.array([[1,2],[3,4],[5,6],[7,8]])

In [35]:
r

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.roll(r,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [39]:
np.roll(r,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.roll(r,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [41]:
~r

array([[-2, -3],
       [-4, -5],
       [-6, -7],
       [-8, -9]])

oeration on numpy string array


In [42]:
q=np.array(["pw","ajay"])

In [43]:
q

array(['pw', 'ajay'], dtype='<U4')

In [44]:
np.char.upper(q)

array(['PW', 'AJAY'], dtype='<U4')

In [45]:
np.char.capitalize(q)

array(['Pw', 'Ajay'], dtype='<U4')

mathamatical function

In [48]:
a1

array([[2, 2, 2],
       [2, 1, 3],
       [1, 2, 2]])

In [49]:
np.sin(a1)

array([[0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.84147098, 0.14112001],
       [0.84147098, 0.90929743, 0.90929743]])

In [50]:
np.cos(a1)

array([[-0.41614684, -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231, -0.9899925 ],
       [ 0.54030231, -0.41614684, -0.41614684]])

In [51]:
np.tan(a1)

array([[-2.18503986, -2.18503986, -2.18503986],
       [-2.18503986,  1.55740772, -0.14254654],
       [ 1.55740772, -2.18503986, -2.18503986]])

In [52]:
np.exp(a1)

array([[ 7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 20.08553692],
       [ 2.71828183,  7.3890561 ,  7.3890561 ]])

In [54]:
np.power(a1,3)

array([[ 8,  8,  8],
       [ 8,  1, 27],
       [ 1,  8,  8]])

In [55]:
np.max(a1)

3

In [58]:
np.mean(a1)

1.8888888888888888

In [57]:
a1

array([[2, 2, 2],
       [2, 1, 3],
       [1, 2, 2]])

In [59]:
np.min(a1)

1

In [60]:
np.std(a1)

0.5665577237325317

In [61]:
np.var(a1)

0.3209876543209877

In [62]:
np.subtract(a1,a)

array([[ 1,  1,  1],
       [ 0, -1,  1],
       [-2, -1, -1]])

In [63]:
a1

array([[2, 2, 2],
       [2, 1, 3],
       [1, 2, 2]])

In [64]:
a

array([[1],
       [2],
       [3]])

In [94]:
a2=np.multiply(a1,a)

In [66]:
np.mod(a1,a)#reminder of division

array([[0, 0, 0],
       [0, 1, 1],
       [1, 2, 2]])

In [68]:
np.sqrt(a1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.73205081],
       [1.        , 1.41421356, 1.41421356]])

searching and sorting in numpy array

In [69]:
e=np.array([5,6,1,2])

In [70]:
e

array([5, 6, 1, 2])

In [71]:
np.sort(e)#Return a sorted copy of an array.

array([1, 2, 5, 6])

In [78]:
f= np.array([5,199,200,6,7,8])

In [79]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [80]:
np.searchsorted(f,170)#Find indices where elements should be inserted to maintain order.Find the indices into a sorted array `a` such that, if the
                  #corresponding elements in `v` were inserted before the indices, the order of `a` would be preserved.


6

In [81]:
f= np.array([5,199,200,6,7,8,0,0,0,0,0])

In [82]:
f

array([  5, 199, 200,   6,   7,   8,   0,   0,   0,   0,   0])

In [85]:
np.count_nonzero(f)

6

In [86]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [87]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 5]),)

In [88]:
np.extract(f>0,f)

array([  5, 199, 200,   6,   7,   8])

In [90]:
f.byteswap()#Swap the bytes of the array elements

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,   576460752303423488,
                          0,                    0,                    0,
                          0,                    0])

In [91]:
import numpy.matlib as nm

In [92]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [93]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

numpy liner algebra function

In [95]:
a1

array([[2, 2, 2],
       [2, 1, 3],
       [1, 2, 2]])

In [96]:
a2

array([[2, 2, 2],
       [4, 2, 6],
       [3, 6, 6]])

In [98]:
np.linalg.det(a2)

-23.999999999999993

In [100]:
np.linalg.inv(a1)#in matrin you can not divide matrix you have inverse

array([[ 1.  ,  0.  , -1.  ],
       [ 0.25, -0.5 ,  0.5 ],
       [-0.75,  0.5 ,  0.5 ]])

In [101]:
a=np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [105]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [106]:
b=np.array([16,8,0])

In [107]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])

In [4]:
d = {"Ram": 500, "Shyam": 300}

In [6]:
np.asarray(d)

array({'Ram': 500, 'Shyam': 300}, dtype=object)

In [9]:
#make an array from tuple iterables 
iterator = (i for i in range(5))
np.fromiter(iterator,int)

array([0, 1, 2, 3, 4])

In [11]:
np.linspace(1,50,150)

array([ 1.        ,  1.32885906,  1.65771812,  1.98657718,  2.31543624,
        2.6442953 ,  2.97315436,  3.30201342,  3.63087248,  3.95973154,
        4.2885906 ,  4.61744966,  4.94630872,  5.27516779,  5.60402685,
        5.93288591,  6.26174497,  6.59060403,  6.91946309,  7.24832215,
        7.57718121,  7.90604027,  8.23489933,  8.56375839,  8.89261745,
        9.22147651,  9.55033557,  9.87919463, 10.20805369, 10.53691275,
       10.86577181, 11.19463087, 11.52348993, 11.85234899, 12.18120805,
       12.51006711, 12.83892617, 13.16778523, 13.4966443 , 13.82550336,
       14.15436242, 14.48322148, 14.81208054, 15.1409396 , 15.46979866,
       15.79865772, 16.12751678, 16.45637584, 16.7852349 , 17.11409396,
       17.44295302, 17.77181208, 18.10067114, 18.4295302 , 18.75838926,
       19.08724832, 19.41610738, 19.74496644, 20.0738255 , 20.40268456,
       20.73154362, 21.06040268, 21.38926174, 21.71812081, 22.04697987,
       22.37583893, 22.70469799, 23.03355705, 23.36241611, 23.69